import { MimeTypes, ObjectKeys, PartialBy } from '@Shared/types/common.cd';

export default interface IResource {
  id: string;
  url: string;
  public: boolean;
  title: string;
  description?: string;
  shortDescription?: string;
  tags?: Array<string>;
  type: MimeTypes;
  createdAt: Date;
  updatedAt?: Date;
  createdBy: string;
  updatedBy?: string;
}

// properties that are auto-generated by the database (not required on create a record)
export type PartialResource = PartialBy<
  IResource,
  'id' | 'public' | 'createdAt'
>;

export type Columns = ObjectKeys<IResource>;